plugin_repo(
  name = "go",
  revision = "v1.21.5",
  plugin = "go-rules",
  owner = "please-build",
)

plugin_repo(
  name = "python",
  revision = "v1.7.4",
  plugin = "python-rules",
  owner = "please-build",
)
