plugin_repo(
  name = "go",
  revision = "v1.19.0",
  plugin = "go-rules",
  owner = "please-build",
)

plugin_repo(
  name = "python",
  revision = "v1.7.0",
  plugin = "python-rules",
  owner = "please-build",
)
